<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>$(SharedTargetFrameworWindows)</TargetFramework>
		<TargetPlatformMinVersion>$(SharedTargetPlatformMinVersion)</TargetPlatformMinVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog" />
		<PackageReference Include="Microsoft.Windows.Compatibility" />
		<PackageReference Include="System.Drawing.Common" />
		<PackageReference Include="Vortice.Direct2D1" />
		<PackageReference Include="Vortice.Direct3D11" />
		<PackageReference Include="Vortice.DirectComposition" />
	</ItemGroup>
</Project>